package dockback.domain.docker

case class DockerInfo(
  id: String,
  containers: Int,
  images: Int,
  driver: String,
  driverStatus: DockerDriverStatus,
  memoryLimit: Boolean,
  swapLimit: Boolean,
  cpuCfsPeriod: Boolean,
  cpuCfsQuota: Boolean,
  ipv4Forwarding: Boolean,
  bridgeNfIptables: Boolean,
  bridgeNfIp6tables: Boolean,
  debug: Boolean,
  nfd: Int,
  oomKillDisable: Boolean,
  nGoRoutines: Int,
  systemTime: String,
  executionDriver: String,
  loggingDriver: String,
  nEventsListener: Int,
  kernelVersion: String,
  operatingSystem: String,
  indexServerAddress: String,
  registryConfig: DockerRegistryConfig,
  initSha1: String,
  initPath: String,
  ncpu: Int,
  memTotal: Long,
  dockerRootDir: String,
  httpProxy: String,
  httpsProxy: String,
  noProxy: String,
  name: String,
  labels:  Map[String, String],
  experimentalBuild: Boolean,
  serverVersion: String,
  clusterStore: String,
  clusterAdvertise: String
)
